apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - elasticsearch.yaml
  - auth-deployment.yaml
  - chat-deployment.yaml
  - ingress.yaml
  - hpa.yaml