// Nexus Platform API Gateway — Cloudflare Worker
// Production deployment — auto-generated by deploy script

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;
    const method = request.method;

    // CORS headers
    const cors = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type,Authorization',
    };

    if (method === 'OPTIONS') {
      return new Response(null, { headers: cors });
    }

    function json(data, status = 200) {
      return new Response(JSON.stringify(data), {
        status,
        headers: { 'Content-Type': 'application/json', ...cors },
      });
    }

    function error(msg, status = 400) {
      return json({ error: msg }, status);
    }

    async function auth(req) {
      const authHeader = req.headers.get('Authorization');
      if (!authHeader || !authHeader.startsWith('Bearer ')) return null;
      const token = authHeader.slice(7);
      try {
        // Simple JWT verify (in production use proper verification)
        const payload = JSON.parse(atob(token.split('.')[1]));
        return payload.sub || null;
      } catch {
        return null;
      }
    }

    try {
      // Health check
      if (path === '/health') {
        return json({
          status: 'ok',
          platform: 'Cloudflare Edge',
          region: request.cf?.colo || 'unknown',
          timestamp: Date.now(),
          version: '1.0.0',
        });
      }

      // Auth routes
      if (path === '/auth/register' && method === 'POST') {
        const body = await request.json();
        const { username, email, password, displayName } = body;

        if (!password || password.length < 8) return error('Password too short');
        if (!displayName) return error('Display name required');

        // Check existing
        const existing = await env.NEXUS_DB.prepare(
          'SELECT id FROM users WHERE username = ? OR email = ?'
        ).bind(username || '', email || '').first();

        if (existing) return error('User already exists', 409);

        const id = crypto.randomUUID();
        const hash = await hashPassword(password);

        await env.NEXUS_DB.prepare(
          'INSERT INTO users (id, username, email, password_hash, display_name) VALUES (?, ?, ?, ?, ?)'
        ).bind(id, username || '', email || '', hash, displayName).run();

        return json({
          user: { id, username, email, displayName },
          accessToken: 'registered',
        }, 201);
      }

      if (path === '/auth/login' && method === 'POST') {
        const body = await request.json();
        const { identifier, password } = body;

        const user = await env.NEXUS_DB.prepare(
          'SELECT * FROM users WHERE username = ? OR email = ? OR phone = ?'
        ).bind(identifier, identifier, identifier).first();

        if (!user) return error('Invalid credentials', 401);

        const valid = await verifyPassword(password, user.password_hash);
        if (!valid) return error('Invalid credentials', 401);

        return json({
          user: {
            id: user.id,
            username: user.username,
            email: user.email,
            displayName: user.display_name,
          },
          accessToken: 'jwt-placeholder',
          expiresIn: 900,
        });
      }

      // Chat routes (authenticated)
      const userId = await auth(request);

      if (path === '/chats' && method === 'GET') {
        if (!userId) return error('Unauthorized', 401);

        const chats = await env.NEXUS_DB.prepare(`
          SELECT c.* FROM chats c
          JOIN chat_participants cp ON c.id = cp.chat_id
          WHERE cp.user_id = ?
          ORDER BY c.updated_at DESC LIMIT 50
        `).bind(userId).all();

        return json({ chats: chats.results });
      }

      if (path.startsWith('/chats/') && path.includes('/messages') && method === 'GET') {
        if (!userId) return error('Unauthorized', 401);
        const chatId = path.split('/')[2];

        const messages = await env.NEXUS_DB.prepare(`
          SELECT * FROM messages WHERE chat_id = ? ORDER BY created_at DESC LIMIT 50
        `).bind(chatId).all();

        return json({ messages: messages.results });
      }

      // Search
      if (path === '/search' && method === 'GET') {
        const query = url.searchParams.get('q') || '';
        if (!query) return json({ results: [] });

        const users = await env.NEXUS_DB.prepare(
          'SELECT id, username, display_name FROM users WHERE username LIKE ? OR display_name LIKE ? LIMIT 20'
        ).bind('%' + query + '%', '%' + query + '%').all();

        return json({ results: users.results });
      }

      // 404
      return json({ error: 'Not Found', path }, 404);

    } catch (err) {
      console.error('Error:', err.message || err);
      return json({ error: 'Internal Server Error' }, 500);
    }
  },
};

// Crypto helpers
async function hashPassword(password) {
  const encoder = new TextEncoder();
  const data = encoder.encode(password);
  const hash = await crypto.subtle.digest('SHA-256', data);
  return btoa(String.fromCharCode(...new Uint8Array(hash)));
}

async function verifyPassword(password, hash) {
  return (await hashPassword(password)) === hash;
}
